Save the score of the played games
clausia/tetromiq pull request #26
Opened 2021-09-29 18:46 UTC by Isamade

The features were implemented but it looks like the code could be written better. Encrypting the saved file has not been implemented. closes #8

2021-09-29 18:53 UTC, clausia commented
@Isamade Thanks 😃 
you can push more commits to this same branch (therefore to this PR), in order to complement what you mentioned in the description, if you think it is convenient

2021-09-29 20:00 UTC, clausia requested changes, later dismissed
I have placed some comments within the code, please check them.

Below I mention comments in general:

- Draw a box where the text box appears to capture the player's nickname, including:
  - black background
  - a frame to highlight this black box
  - centered texts, both the one that asks for the nickname to be captured and the text that the player captures, centered in its text box
Something like this:
![image](https://user-images.githubusercontent.com/1554515/135338694-6f47e1a6-1605-4b9b-8bda-8a0a12b8ff09.png)

- Regarding the score table:
  - use colors that are very noticeable over black
  - the texts must be centered between them, and the columns distributed in the width of the window
  - include the rank, which is in descending order according to the scores, for example:
![image](https://user-images.githubusercontent.com/1554515/135339299-310d2cf7-6b6c-4d42-9064-c5f19a9b86ea.png)
  - limit the table to the first 15 or 20 scores, the ones that fit well in the window
  - There is a bug in the score table view, if I press enter several times, it causes the last name captured to be displayed several times, example:
![image](https://user-images.githubusercontent.com/1554515/135339148-aaee4690-d183-4505-b17d-87e9c19333f7.png)

2021-09-29 20:00 UTC, clausia commented on src/tetromiq.py
> +    read_high_score = open(Path("../resources/Scores.txt"), "r")
All this new functionality that has to do with capturing the player's nickname and saving and displaying the scores, place it in a _new function_, in general all the team must avoid as much as possible to increase the number of lines within the existing functions, so that we can better understand the changes we are making, if you need objects that are defined here (`def game()`), you must send them as parameters to this _new function_ that you must define,

2021-09-29 20:00 UTC, clausia commented on resources/Scores.txt
> +10=Alberto
Name this file using lowercase only, i.e.: **`scores.txt`**

2021-09-29 20:00 UTC, clausia commented on src/tetromiq.py
> +
By default, place the cursor in the capture text box, it does not make much sense to wait for the player to click on the text box, since there is no other action that he/her can do at this point in the game, due to that no need to wait for mouse click on text box.

Simply, the player should be able to capture his/her nickname immediately after the _Game Over_ occurs

2021-09-29 20:00 UTC, clausia commented on src/tetromiq.py
> +
Create the table in a separate function.

2021-09-29 20:00 UTC, Isamade commented
Okay, I'll rather move to the visual effects/animations now and come back to this much later if there is time though

2021-09-30 21:08 UTC, clausia commented
@Isamade 
What I have commented on the visual part is only a suggestion, it does not necessarily have to be in this way, not the colors or the shapes, only that it is clear for the player and in general the elements centered on the screen.

2021-10-01 12:05 UTC, Isamade commented
The user likes to know when their scores have improved, so they will be allowed to know that information by saving a table with the scores generated in the different matches.

Consider:

 Allow user to capture their nickname that will be shown in the scores table
 Show the score table every time a game ends
 Save it in an encrypted file, so scores are not lost

2021-10-01 19:50 UTC, clausia reviewed
Looks good!

It just keeps happening the situation that if I press enter while in the table, it adds the last nickname captured several times, but it only happened with the first time I played, but not with the second time:

![image](https://user-images.githubusercontent.com/1554515/135678396-2c0e764b-3ea5-40cf-aeb2-0cec7e61d554.png)

2021-10-01 19:50 UTC, clausia commented on src/tetromiq.py
> +                if event.key == pygame.K_p and not game_over:
One question: why is it needed to ask `if not game_over`?

2021-10-01 19:51 UTC, clausia commented on src/tetromiq.py
> +
Ok, we can do this for a next version

2021-10-01 23:07 UTC, Isamade commented
I tried several times, pushing the enter key while in the table didn't have an effect

2021-10-01 23:09 UTC, clausia commented
> I tried several times, pushing the enter key while in the table didn't have an effect

@Isamade 
I think this happens when `scores.txt` is empty, that's why happened only the very first time

2021-10-02 03:22 UTC, clausia commented
> I tried several times, pushing the enter key while in the table didn't have an effect

I tried again and everything was perfect!
I don't know what happened, I'm glad that this didn't happened again 😺

2021-10-02 03:23 UTC, clausia approved these changes
All good 😀

2021-10-02 03:25 UTC, iguanajazz commented
> > I tried several times, pushing the enter key while in the table didn't have an effect
> 
> I tried again and everything was perfect! I don't know what happened, I'm glad that this didn't happened again 😺

I tested too and all good! :shipit:

2021-10-02 03:29 UTC, iguanajazz approved these changes

2021-10-02 11:53 UTC, merged